# Generated by Django 4.0.2 on 2022-08-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=20)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
